fix: change paint flags to SpannableString in strikethrough prices
Decathlon/vitamin-android pull request #112
Opened 2022-04-06 09:18 UTC by charlottemougenot

## Changes description

Change paint flag to SpannableString to have clear text on strikethrough price

## Context

Closes #111 

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [X] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [X] Check your code additions will fail neither code linting checks.
- [X] I have reviewed the submitted code.
- [X] I have tested on a phone device/emulator.
- [X] I have tested on a tablet device/emulator.
- [X] I have tested on a large screen device/emulator.
- [X] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

## Screenshots
Before : 
![image](https://user-images.githubusercontent.com/54030002/161939531-6d871479-ea13-4a46-bd9c-bd34ecf06aaf.png)
After : 
![image](https://user-images.githubusercontent.com/54030002/161941011-2d0aaec6-384c-451d-aa53-b63f3dd2957d.png)

## Other information

2022-04-06 09:28 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/62ac2962b2dd627a/build/2b03faa3-1e9f-4139-a49d-76fb0cce95dd/artifact/5339f44ed27ca506/p/cec7342d4bbd13edd332ba51f1a875e6

2022-04-06 09:31 UTC, GerardPaligot requested changes

2022-04-06 09:31 UTC, GerardPaligot commented on prices/src/main/java/com/decathlon/vitamin/prices/VitaminPrices.kt
> +        this.text = string
Maybe we can extract this traitement (and all others) in `foundation` to avoid error in the future?

2022-04-06 13:53 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/62ac2962b2dd627a/build/7065e606-89dc-44fa-a507-f271cfc9522c/artifact/a24f67bcdf2c00f9/p/73b1a53dfb6adb8933f06c4d18c519e2

2022-04-07 07:46 UTC, GerardPaligot approved these changes

2022-04-07 07:48 UTC, merged