Add dropdown menu for Popup/ListPopup and TextInputLayout Filled/Outlined
Decathlon/vitamin-android pull request #51
Opened 2021-11-05 12:22 UTC by GerardPaligot

## Changes description 🧑‍💻

* Upgrade Kotlin to 1.5.31.
* Add vtmnContentTertiary Vitamin semantic color.
* Create internal dropdown module for menus and text inputs.
* Create menus module for dropdown popup and list popup.
* Add dropdown for TextInput Filled/Outlined.

## Context 🤔

Closes #43 

## Checklist ✅

 - [x] I have reviewed the submitted code
 - [x] I have tested on a phone device/emulator
 - [x] I have tested on a tablet device/emulator
 - [x] I have tested on a kiosk device/emulator

## Screenshots 📸

#### Phone

https://user-images.githubusercontent.com/1913901/140509406-c3f8c580-9280-4679-aad7-87da7dc08aa0.mp4

#### Tablet

https://user-images.githubusercontent.com/1913901/140509519-8b687b1b-fd5d-4eb7-83f9-d419b13be082.mp4

#### Kiosk

https://user-images.githubusercontent.com/1913901/140509460-94178ad9-3b7a-4bd6-b84b-aa34930c7c1f.mp4

2021-11-08 16:04 UTC, MaximeJineMaraval requested changes

2021-11-10 11:34 UTC, GerardPaligot commented on internal/dropdown/src/main/java/com/decathlon/vitamin/dropdown/VitaminDropdownAdapter.kt
> +    private class ArrayFilter<T>(val list: List<T>, val adapter: BaseAdapter) : Filter() {
Yes, it is required by the `AutocompleteTextView` in a `TextInputLayout`...

2021-11-10 11:37 UTC, GerardPaligot commented on internal/dropdown/src/main/java/com/decathlon/vitamin/dropdown/VitaminDropdownAdapter.kt
> +private class ViewHolder(view: View) {
Not at all. Remove both class outside the Adapter!

2021-11-10 12:01 UTC, GerardPaligot commented on internal/dropdown/src/main/res/layout/vtmn_dropdown_item.xml
> +    style="?attr/vtmnDropDownItemStyle"
There is no impact. I use the same style for the simple dropdown item and this one and text attributes is ignored for this one. I'm open to your feedback:

* I create two styles and ask to consumers to declare both styles on their theme if they use only this artifact
* I create a single style for both layout but there is some attributes which is ignored for this one. But for consumers, they need to configure and override only one style too.

I'm not sure what is the best option.

2021-11-16 09:45 UTC, MaximeJineMaraval commented on text-inputs/README.md
> +The Vitamin subclass of `MaterialAutoCompleteTextView`, `VitaminDropdownEditText`, declare 3
Should not be "declare 2"?

2021-11-16 09:45 UTC, MaximeJineMaraval commented on menus/README.md
> +The Vitamin subclass of `ListPopupWindow`, `VitaminListMenu`, declare 3
Should not be "declare 2"?

2021-11-16 09:45 UTC, MaximeJineMaraval commented on internal/dropdown/src/main/res/layout/vtmn_dropdown_item.xml
> +    style="?attr/vtmnDropDownItemStyle"
Ok, understood. 
I think we could keep this version right now, as it's easier to use for the user. But this should be re-think if we have to add more complexity later.

2021-11-16 10:13 UTC, MaximeJineMaraval approved these changes

2021-11-16 10:29 UTC, merged