Feat: Add snackbars
Decathlon/vitamin-android pull request #98
Opened 2022-01-28 16:21 UTC by charlottemougenot

## Changes description

Add material snackbars theming

## Context

Closes #65 

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [X] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [X] Check your code additions will fail neither code linting checks.
- [X] I have reviewed the submitted code.
- [X] I have tested on a phone device/emulator.
- [X] I have tested on a tablet device/emulator.
- [X] I have tested on a large screen device/emulator.
- [X] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

## Screenshots

#### Phone
##### Light
![snackbars_phone_light](https://user-images.githubusercontent.com/54030002/151579271-37020486-b218-4b01-811e-52fbc2f92632.gif)

##### Dark
![snackbars_phone_dark](https://user-images.githubusercontent.com/54030002/151579285-dc0f70da-e87a-41c3-9d1e-a8d3d4334d1d.gif)

#### Tablet

![snackbars_tablet_light](https://user-images.githubusercontent.com/54030002/151582965-a1df34b6-a427-4188-85d1-6a8a3fb5c7a0.gif)

#### Large screen

![snackbars_kiosk22_light](https://user-images.githubusercontent.com/54030002/151583005-c94d8740-2d64-4ee4-9997-6bb60354371a.gif)

![snackbars_kiosk24_light](https://user-images.githubusercontent.com/54030002/151582978-834f3aee-d69f-4d04-aef1-64e74d569feb.gif)

2022-01-31 15:05 UTC, MaximeJineMaraval requested changes

2022-01-31 15:05 UTC, MaximeJineMaraval commented on sample/src/main/res/layout/fragment_snackbars.xml
> +        android:id="@+id/btn_show_snackbar_with_button"
It shouldn't be `@+id/btn_show_long_snackbar`?

2022-01-31 15:05 UTC, MaximeJineMaraval commented on sample/src/main/res/layout/fragment_snackbars.xml
> +        android:id="@+id/btn_show_long_snackbar"
It shouldn't be `@+id/btn_show_snackbar_with_button`?

2022-02-03 15:10 UTC, GerardPaligot approved these changes

2022-02-03 15:29 UTC, MaximeJineMaraval approved these changes

2022-02-03 15:30 UTC, merged